routes/admin.php
<?php
use App\Http\Controllers\Admin\AdminBanUserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserActionsController;
use App\Http\Controllers\Admin\AdminViolateUserController;
use App\Http\Controllers\Admin\AdminWarnUserController;
use Illuminate\Support\Facades\Route;
/*
|-------------------------------------------------------------------------------
| Admin section
|-------------------------------------------------------------------------------
| Prefix:         admin/ OR .admin
| Controller:     Admin/AdminController
| Method:         MIXED
| Description:    Admin actions
*/
Route::middleware(['auth', 'verified'])->group(function () {

    Route::prefix('admin')
        ->middleware(['is_admin'])
        ->name('admin.')
        ->group(function () {

            Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

            // User actions
            Route::controller(AdminUserActionsController::class)->group(function () {
                Route::get('/view_user/{user_id}', 'viewUser')->name('view_user')->where('user_id', '[0-9]+');
                Route::get('/view_user_logins/{user_id}', 'viewUserLogins')->name('view_user_logins')->where('user_id', '[0-9]+');
                Route::get('/view_users', 'viewAllUsers')->name('view_users');
                Route::post('/find_user', 'findUser')->name('find_user');
                Route::post('/verify_user', 'verifyUser')->name('verify_user');
                Route::get('/delete_user/{user_id}', 'deleteUser')->name('delete_user')->where('user_id', '[0-9]+');
                Route::get('/user_status/{user_id}', 'changeUserStatus')->name('user_status')->where('user_id', '[0-9]+');
                // messages
                Route::get('/message_new', 'newMessage')->name('message_new');
                Route::post('/message_system_save', 'saveUserMessage')->name('message_system_save');
                Route::get('/message_user/{user_id}', 'newUserMessage')->name('message_user')->where('user_id', '[0-9]+');
                Route::post('/message_user_save', 'saveUserMessage')->name('message_user_save');
                // Clone users
                Route::get('/clone_user/{user_id}', 'cloneUser')->name('clone_user')->where('user_id', '[0-9]+');

            });


            // Group actions
            Route::controller(\App\Http\Controllers\Admin\GroupController::class)->group(function () {
                // Viewing
                Route::get('/group_all', 'viewGroups')->name('group_all');
                Route::get('/group_view/{id}', 'viewGroup')->name('group_view')->where('id', '[0-9]+');


            });
            // Warned users
            Route::post('/warn_user', [AdminWarnUserController::class, 'warnUser'])->name('warn_user');

            // Banned users
            Route::controller(AdminBanUserController::class)->group(function () {
                Route::post('/ban_user', 'banUser')->name('ban_user');
                Route::get('/unban_user/{user_id}', 'unbanUser')->name('unban_user')->where('user_id', '[0-9]+');
                Route::get('/unban_all_users', 'unbanAllExpiredBannedUsers')->name('unban_all_users');
                Route::get('/view_banned_users', 'viewAllBannedUsers')->name('view_banned_users');
            });

            // Violations reported users
            Route::controller(AdminViolateUserController::class)->group(function () {
                Route::get('/violation_pending', 'viewAllPendingViolations')->name('violation_pending');
                Route::get('/violation_all', 'viewAllViolations')->name('violation_all');
                Route::get('/reported_type/{violation_type}', 'viewAllViolationsByType')->name('reported_type');
                Route::get('/violations_by_user/{user_id}', 'viewReportedByUserViolations')->name('violations_by_user')->where('user_id', '[0-9]+');
                Route::get('/violations_against_user/{user_id}', 'viewReportedAgainstUserViolations')->name('violations_against_user')->where('user_id', '[0-9]+');
            });


        });

});

routes/web.php
<?php


use App\Http\Controllers\BannedController;
use App\Http\Controllers\Groups\ClubController;
use App\Http\Controllers\News\RSSController;
use App\Http\Controllers\News\VideoController;
use App\Http\Controllers\System\MessageController;
use App\Http\Controllers\Users\DashController;
use App\Http\Controllers\Users\UserActionsController;
use App\Http\Controllers\Users\UserController;
use App\Http\Controllers\Users\UserViolationsController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

try {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/clear_cache', function() {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('event:clear');
        $exitCode = Artisan::call('route:clear');
        $exitCode = Artisan::call('view:clear');
        return 'DONE'; //Return anything
    });

    Route::get('/banned', [BannedController::class, 'banned'])->name('banned');
    Route::post('/restore_ban', [BannedController::class, 'restoreBan'])->name('restore_ban');
    /*
    |--------------------------------------------------------------------------
    | Site web Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::middleware(['auth', 'verified'])->group(function () {

        Route::get('/policies', [DashController::class, 'viewPolicyPage'])->name('policies');
        Route::get('/view_policy/{id}', [DashController::class, 'viewPolicyTypePage'])->name('view_policy');


        /*
        |-------------------------------------------------------------------------------
        | User section
        |-------------------------------------------------------------------------------
        | Prefix:         user/ OR .user
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    User actions
        */
        Route::prefix('user')
            ->name('user.')
            ->middleware(['is_banned', 'is_online'])
            //->middleware(['forbid-banned-user', 'is_online'])
            ->group(function () {

                // General routes and settings
                Route::controller(DashController::class)->group(function () {
                    Route::get('/dashboard', 'index')->name('dashboard');
                });


                Route::controller(UserController::class)->group(function () {
                    Route::get('/user_profile', 'viewProfile')->name('user_profile');
                    Route::get('/directory', 'viewDirectory')->name('directory')->middleware('is_warned');
                    Route::get('/public/{id}', 'viewPublicProfile')->name('public')->middleware('is_warned');
                    Route::get('/warning_page', 'viewWarningPage')->name('warning_page');
                });

                Route::middleware(['is_warned'])->group(function () {

                    // Basic account actions
                    Route::controller(UserActionsController::class)->group(function () {
                        Route::get('/user_change_password', 'changePassword')->name('user_change_password');
                        Route::post('/user_save_password', 'savePassword')->name('user_save_password');
                        Route::get('/user_change_email', 'changeEmail')->name('user_change_email');
                        Route::post('/user_save_email', 'saveEmail')->name('user_save_email');
                        Route::post('/user_change_visibility', 'toggleVisibility')->name('user_change_visibility');
                        Route::post('/user_delete_account', 'deleteAccount')->name('user_delete_account');
                    });

                    // Violations
                    Route::controller(UserViolationsController::class)->group(function () {
                        Route::get('/violation_create', 'violationCreate')->name('violation_create');
                        Route::post('/violation_update', 'violationUpdate')->name('violation_update');
                        Route::post('/violation_save', 'violationSave')->name('violation_save');
                        Route::get('/violation_view/{id}', 'violationView')->name('violation_view');
                        Route::get('/violation_reported', 'violationViewReported')->name('violation_reported');
                        Route::get('/violation_against_user', 'violationViewReportedAgainst')->name('violation_against_user');
                    });

                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Clubs section
        |-------------------------------------------------------------------------------
        | Prefix:         club/ OR .club
        | Controller:     Groups/ClubController, ManageClubController
        | Method:         MIXED
        | Description:    Group actions
        */
        Route::prefix('club')
            ->name('club.')
            ->middleware(['is_banned', 'is_warned'])
            ->group(function () {

                // Basic routes
                Route::controller(ClubController::class)->group(function () {
                    Route::get('/view/{id}', 'view')->name('view');
                    Route::get('/edit/{id}', 'create')->name('edit');
                    Route::post('/update', 'create')->name('update');
                    Route::post('/delete_all', 'destroyAll')->name('delete_all');
                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Messages section
        |-------------------------------------------------------------------------------
        | Prefix:         messages/ OR .messages
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    messages actions
        */
        Route::prefix('messages')
            ->name('messages.')
            ->group(function () {
                Route::middleware(['is_warned'])->controller(MessageController::class)->group(function () {
                    Route::get('/', 'index')->name('messages');
                    Route::get('/create', 'create')->name('create');
                    Route::post('/', 'store')->name('store');
                    Route::get('{id}', 'show')->name('show');
                    Route::put('{id}', 'update')->name('update');
                });
       });

        /*
        |-------------------------------------------------------------------------------
        | News section
        |-------------------------------------------------------------------------------
        | Prefix:         news/ OR .news
        | Controller:     News/RSSController
        | Method:         MIXED
        | Description:    news actions
        */
        Route::prefix('news')
            ->name('news.')
            ->group(function () {
                Route::controller(RSSController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('feed/{slug}', 'loadFeed')->name('feed');
                    Route::get('ana', 'getANA')->name('ana');
                });
            });

        /*
        |-------------------------------------------------------------------------------
        | Video section
        |-------------------------------------------------------------------------------
        | Prefix:         video/ OR .video
        | Controller:     News/VideoController
        | Method:         MIXED
        | Description:    Video actions
        */
        Route::prefix('video')
            ->name('video.')
            ->group(function () {
                Route::controller(VideoController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('channel/{slug}', 'loadChannel')->name('channel');
                    Route::get('playlist/{slug}', 'loadChannel')->name('playlist');
                    Route::get('url', 'loadChannel')->name('url');
                    Route::get('search', 'loadSearchVideos')->name('search');
                });
            });


    });



    /*
    |-------------------------------------------------------------------------------
    | Auth Routes
    |-------------------------------------------------------------------------------
    | Prefix:         NONE
    | Controller:     RegisteredUserController, AuthenticatedSessionController, PasswordResetLinkController
    | Method:         MIXED
    | Description:    Auth routes
    */
    require __DIR__.'/auth.php';

}catch (\Throwable $e){
    Log::error($e->getMessage());
    return view('welcome');
}

app/Http/Controllers/Groups/MemberController.php
<?php

namespace App\Http\Controllers\Groups;

use App\Http\Controllers\Controller;
use App\Http\Traits\GroupTrait;
use App\Models\Groups\Group;

class MemberController extends Controller
{
    use GroupTrait;


    public function index(Group $group)
    {
        return view('groups.group.members.index', [
            'group' => $group,
        ]);
    }
}

app/Http/Controllers/Members/GalleryController.php
<?php

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;

class GalleryController extends Controller
{
    //
}

app/Http/Controllers/Members/IndexController.php
<?php

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    //
}

app/Http/Controllers/Members/LeaveController.php
<?php

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use App\Models\Participant;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class LeaveController extends Controller
{


    public function leaveForum(Request $request): JsonResponse
    {
        $request->validate([
            'forum_id' => 'required|integer',
            'user_id' => 'required|integer',
        ]);
        try{
            Participant::where('forum_id', $request->input('forum_id'))
            ->where('user_id', $request->input('user_id'))->delete();

            return response()->json([
                'result' => 'Success'
            ]);
        }catch (Exception $e){
            Log::error($e->getMessage());
            return response()->json([
                'result' => 'Error',
            ]);
        }

    }
}

app/Http/Controllers/Members/ResearchController.php
<?php
/**
 * ResearchController | actions for views/users
 *
 * @package Users
 * @subpackage Activities
 * @author Andre Board <dre.board@gmail.com>
 * @version 1.0
 * @access public
 * @see https://github.com/dreboard/coin-app
 * @copyright none
 */
namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use App\Models\Project;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class ResearchController extends Controller
{



    /**
     * View Research intro page
     *
     * @return Application|Factory|View
     */
    public function index()
    {

        $new_projects = Project::where('private', 0)
            ->orderBy('created_at', 'desc')->limit(2)->get();
        $all_projects = Project::with(['user:id,name'])->select('id', 'title', 'user_id')->where('private', 0)->get();
        //dd($all_projects);
        return view('members.research.index', [
            'new_projects' => $new_projects,
            'all_projects' => $all_projects
        ]);
    }

}

resources/views/members/books/books.blade.php
@extends('layouts.user.main')
@section('pageTitle', 'Writers Area')
@section('content')

    <div class="row">
        <div class="col-6 float-start">
            <h3 class="mt-4">Writers Area</h3>
        </div>
        <div class="col-6">
                <div class="dropdown mt-4 float-end">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        CHANGE
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item"
                               href="{{ route('user.user_profile', ['id' => auth()->user()->id]) }}">Back To Settings</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{{ route('user.edit_public', ['user' => auth()->user()->id]) }}">Edit This
                                Profile</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{{ route('user.user_edit_avatar', ['user' => auth()->user()->id]) }}">Change Image</a>
                        </li>
                    </ul>
                </div>
        </div>
    </div>

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{ route('user.dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('member.writers') }}">Writers Area</a></li>
            <li class="breadcrumb-item"><a href="{{ route('user.public', ['id' => auth()->user()->id]) }}">My
                    Articles</a></li>
    </ol>

    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8">


            <div class="table-responsive">
                <table id="user_directory_tbl" class="table datatable">
                    <thead>
                    <tr>
                        <th class="fw-bold">Title</th>
                        <th class="fw-bold">Author</th>
                        <th class="fw-bold">Type</th>
                        <th class="fw-bold">Review</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th class="fw-bold">Title</th>
                        <th class="fw-bold">Author</th>
                        <th class="fw-bold">Type</th>
                        <th class="fw-bold">Review</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    @foreach ($books as $book)
                        <tr>
                            <td class="text-start" style="width: 40%"><a href="{{ route('member.view_book', ['id' => $book->id]) }}">{{ $book->title }}</a></td>
                            <td class="text-start"><a href="{{ route('member.view_book', ['id' => $book->id]) }}">{{ $book->author }}</a></td>
                            <td class="text-start">
                                <a href="{{ route('member.view_book', ['id' => $book->id]) }}">{{ $book->publication_type }}</a>
                            </td>
                            <td class="text-start">
                                <a href="{{ route('member.review_book', ['id' => $book->id]) }}">Review</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Side widgets-->
        @include('members.writers.partials.side')
    </div>

@endsection

resources/views/members/books/view.blade.php
@extends('layouts.user.main')
@section('pageTitle', 'View Book')
@section('content')

    <div class="row">
        <div class="col-6 float-start">
            <h3 class="mt-4">{{ $book->title }}</h3>
        </div>
        <div class="col-6">
                <div class="dropdown mt-4 float-end">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        CHANGE
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item"
                               href="{{ route('user.user_profile', ['id' => auth()->user()->id]) }}">Back To Settings</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{{ route('user.edit_public', ['user' => auth()->user()->id]) }}">Edit This
                                Profile</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{{ route('user.user_edit_avatar', ['user' => auth()->user()->id]) }}">Change Image</a>
                        </li>
                    </ul>
                </div>
        </div>
    </div>

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{ route('user.dashboard') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('member.writers') }}">Writers Area</a></li>
            <li class="breadcrumb-item"><a href="{{ route('user.public', ['id' => auth()->user()->id]) }}">My
                    Articles</a></li>
    </ol>

    <div class="row">
        <!-- Blog entries-->
        <div class="col-lg-8">

            <table class="table">
                <tr>
                    <th scope="row">Author</th>
                    <td>{{ $book->author }}</td>
                </tr>
                <tr>
                    <th scope="row">ISBN</th>
                    <td>{{ $book->isbn }}</td>
                </tr>
                <tr>
                    <th scope="row">Publisher</th>
                    <td colspan="2">{{ $book->publisher }}</td>
                </tr>
            </table>

            <div>
                <p class="mt-3 mb-3">{!! $book->description !!}</p>
            </div>

            <hr />
            <h3>Reviews</h3>
            @forelse($book->reviews as $review)
                <p>{!! $review->comment !!}</p>
            @empty
                <p>No reviews yet</p>
            @endforelse
        </div>

        <!-- Side widgets-->
        @include('members.writers.partials.side')
    </div>

@endsection