routes/admin.php
<?php
use App\Http\Controllers\Admin\AdminBanUserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserActionsController;
use App\Http\Controllers\Admin\AdminViolateUserController;
use App\Http\Controllers\Admin\AdminWarnUserController;
use Illuminate\Support\Facades\Route;
/*
|-------------------------------------------------------------------------------
| Admin section
|-------------------------------------------------------------------------------
| Prefix:         admin/ OR .admin
| Controller:     Admin/AdminController
| Method:         MIXED
| Description:    Admin actions
*/
Route::middleware(['auth', 'verified'])->group(function () {

    Route::prefix('admin')
        ->middleware(['is_admin'])
        ->name('admin.')
        ->group(function () {

            Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

            // User actions
            Route::controller(AdminUserActionsController::class)->group(function () {
                Route::get('/view_user/{user_id}', 'viewUser')->name('view_user')->where('user_id', '[0-9]+');
                Route::get('/view_user_logins/{user_id}', 'viewUserLogins')->name('view_user_logins')->where('user_id', '[0-9]+');
                Route::get('/view_users', 'viewAllUsers')->name('view_users');
                Route::post('/find_user', 'findUser')->name('find_user');
                Route::post('/verify_user', 'verifyUser')->name('verify_user');
                Route::get('/delete_user/{user_id}', 'deleteUser')->name('delete_user')->where('user_id', '[0-9]+');
                Route::get('/user_status/{user_id}', 'changeUserStatus')->name('user_status')->where('user_id', '[0-9]+');
                // messages
                Route::get('/message_new', 'newMessage')->name('message_new');
                Route::post('/message_system_save', 'saveUserMessage')->name('message_system_save');
                Route::get('/message_user/{user_id}', 'newUserMessage')->name('message_user')->where('user_id', '[0-9]+');
                Route::post('/message_user_save', 'saveUserMessage')->name('message_user_save');
                // Clone users
                Route::get('/clone_user/{user_id}', 'cloneUser')->name('clone_user')->where('user_id', '[0-9]+');

            });


            // Group actions
            Route::controller(\App\Http\Controllers\Admin\GroupController::class)->group(function () {
                // Viewing
                Route::get('/group_all', 'viewGroups')->name('group_all');
                Route::get('/group_view/{id}', 'viewGroup')->name('group_view')->where('id', '[0-9]+');


            });
            // Warned users
            Route::post('/warn_user', [AdminWarnUserController::class, 'warnUser'])->name('warn_user');

            // Banned users
            Route::controller(AdminBanUserController::class)->group(function () {
                Route::post('/ban_user', 'banUser')->name('ban_user');
                Route::get('/unban_user/{user_id}', 'unbanUser')->name('unban_user')->where('user_id', '[0-9]+');
                Route::get('/unban_all_users', 'unbanAllExpiredBannedUsers')->name('unban_all_users');
                Route::get('/view_banned_users', 'viewAllBannedUsers')->name('view_banned_users');
            });

            // Violations reported users
            Route::controller(AdminViolateUserController::class)->group(function () {
                Route::get('/violation_pending', 'viewAllPendingViolations')->name('violation_pending');
                Route::get('/violation_all', 'viewAllViolations')->name('violation_all');
                Route::get('/reported_type/{violation_type}', 'viewAllViolationsByType')->name('reported_type');
                Route::get('/violations_by_user/{user_id}', 'viewReportedByUserViolations')->name('violations_by_user')->where('user_id', '[0-9]+');
                Route::get('/violations_against_user/{user_id}', 'viewReportedAgainstUserViolations')->name('violations_against_user')->where('user_id', '[0-9]+');
            });


        });

});

routes/web.php
<?php


use App\Http\Controllers\BannedController;
use App\Http\Controllers\Groups\ClubController;
use App\Http\Controllers\News\RSSController;
use App\Http\Controllers\News\VideoController;
use App\Http\Controllers\System\MessageController;
use App\Http\Controllers\Users\DashController;
use App\Http\Controllers\Users\UserActionsController;
use App\Http\Controllers\Users\UserController;
use App\Http\Controllers\Users\UserViolationsController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

try {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/clear_cache', function() {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('event:clear');
        $exitCode = Artisan::call('route:clear');
        $exitCode = Artisan::call('view:clear');
        return 'DONE'; //Return anything
    });

    Route::get('/banned', [BannedController::class, 'banned'])->name('banned');
    Route::post('/restore_ban', [BannedController::class, 'restoreBan'])->name('restore_ban');
    /*
    |--------------------------------------------------------------------------
    | Site web Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::middleware(['auth', 'verified'])->group(function () {

        Route::get('/policies', [DashController::class, 'viewPolicyPage'])->name('policies');
        Route::get('/view_policy/{id}', [DashController::class, 'viewPolicyTypePage'])->name('view_policy');


        /*
        |-------------------------------------------------------------------------------
        | User section
        |-------------------------------------------------------------------------------
        | Prefix:         user/ OR .user
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    User actions
        */
        Route::prefix('user')
            ->name('user.')
            ->middleware(['is_banned', 'is_online'])
            //->middleware(['forbid-banned-user', 'is_online'])
            ->group(function () {

                // General routes and settings
                Route::controller(DashController::class)->group(function () {
                    Route::get('/dashboard', 'index')->name('dashboard');
                });


                Route::controller(UserController::class)->group(function () {
                    Route::get('/user_profile', 'viewProfile')->name('user_profile');
                    Route::get('/directory', 'viewDirectory')->name('directory')->middleware('is_warned');
                    Route::get('/public/{id}', 'viewPublicProfile')->name('public')->middleware('is_warned');
                    Route::get('/warning_page', 'viewWarningPage')->name('warning_page');
                });

                Route::middleware(['is_warned'])->group(function () {

                    // Basic account actions
                    Route::controller(UserActionsController::class)->group(function () {
                        Route::get('/user_change_password', 'changePassword')->name('user_change_password');
                        Route::post('/user_save_password', 'savePassword')->name('user_save_password');
                        Route::get('/user_change_email', 'changeEmail')->name('user_change_email');
                        Route::post('/user_save_email', 'saveEmail')->name('user_save_email');
                        Route::post('/user_change_visibility', 'toggleVisibility')->name('user_change_visibility');
                        Route::post('/user_delete_account', 'deleteAccount')->name('user_delete_account');
                    });

                    // Violations
                    Route::controller(UserViolationsController::class)->group(function () {
                        Route::get('/violation_create', 'violationCreate')->name('violation_create');
                        Route::post('/violation_update', 'violationUpdate')->name('violation_update');
                        Route::post('/violation_save', 'violationSave')->name('violation_save');
                        Route::get('/violation_view/{id}', 'violationView')->name('violation_view');
                        Route::get('/violation_reported', 'violationViewReported')->name('violation_reported');
                        Route::get('/violation_against_user', 'violationViewReportedAgainst')->name('violation_against_user');
                    });

                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Clubs section
        |-------------------------------------------------------------------------------
        | Prefix:         club/ OR .club
        | Controller:     Groups/ClubController, ManageClubController
        | Method:         MIXED
        | Description:    Group actions
        */
        Route::prefix('club')
            ->name('club.')
            ->middleware(['is_banned', 'is_warned'])
            ->group(function () {

                // Basic routes
                Route::controller(ClubController::class)->group(function () {
                    Route::get('/view/{id}', 'view')->name('view');
                    Route::get('/edit/{id}', 'create')->name('edit');
                    Route::post('/update', 'create')->name('update');
                    Route::post('/delete_all', 'destroyAll')->name('delete_all');
                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Messages section
        |-------------------------------------------------------------------------------
        | Prefix:         messages/ OR .messages
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    messages actions
        */
        Route::prefix('messages')
            ->name('messages.')
            ->group(function () {
                Route::middleware(['is_warned'])->controller(MessageController::class)->group(function () {
                    Route::get('/', 'index')->name('messages');
                    Route::get('/create', 'create')->name('create');
                    Route::post('/', 'store')->name('store');
                    Route::get('{id}', 'show')->name('show');
                    Route::put('{id}', 'update')->name('update');
                });
       });

        /*
        |-------------------------------------------------------------------------------
        | News section
        |-------------------------------------------------------------------------------
        | Prefix:         news/ OR .news
        | Controller:     News/RSSController
        | Method:         MIXED
        | Description:    news actions
        */
        Route::prefix('news')
            ->name('news.')
            ->group(function () {
                Route::controller(RSSController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('feed/{slug}', 'loadFeed')->name('feed');
                    Route::get('ana', 'getANA')->name('ana');
                });
            });

        /*
        |-------------------------------------------------------------------------------
        | Video section
        |-------------------------------------------------------------------------------
        | Prefix:         video/ OR .video
        | Controller:     News/VideoController
        | Method:         MIXED
        | Description:    Video actions
        */
        Route::prefix('video')
            ->name('video.')
            ->group(function () {
                Route::controller(VideoController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('channel/{slug}', 'loadChannel')->name('channel');
                    Route::get('playlist/{slug}', 'loadChannel')->name('playlist');
                    Route::get('url', 'loadChannel')->name('url');
                    Route::get('search', 'loadSearchVideos')->name('search');
                });
            });


    });



    /*
    |-------------------------------------------------------------------------------
    | Auth Routes
    |-------------------------------------------------------------------------------
    | Prefix:         NONE
    | Controller:     RegisteredUserController, AuthenticatedSessionController, PasswordResetLinkController
    | Method:         MIXED
    | Description:    Auth routes
    */
    require __DIR__.'/auth.php';

}catch (\Throwable $e){
    Log::error($e->getMessage());
    return view('welcome');
}

app/Models/Groups/Settings.php
<?php

namespace App\Models\Groups;

use Database\Factories\Groups\SettingsFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Settings extends Model
{
    use HasFactory;

    protected $table = 'group_settings';

    protected $fillable = [
        'group_id',
        'edit',
        'posts',
        'events',
        'committees',
        'officers',
        'positions',
        'announcements',
        'members',
        'elections',
        'media',
    ];

    /**
     * Get user for the post.
     */
    public function group(): BelongsTo
    {
        return $this->belongsTo(Group::class);
    }

    /**
     * Create a new factory instance for the model.
     *
     * @return SettingsFactory
     */
    protected static function newFactory(): SettingsFactory
    {
        return SettingsFactory::new();
    }
}

app/Models/Users/Login.php
<?php

namespace App\Models\Users;

use App\Models\User;
use Database\Factories\UserFactory;
use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Login extends Model
{
    use HasFactory;

    //protected $dateFormat = 'l jS F Y, g:ia';
    public $timestamps = false;
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime:l jS F Y, g:ia',
    ];

    /**
     * Prepare a date for array / JSON serialization.
     *
     * @param DateTimeInterface $date
     * @return string
     */
    protected function serializeDate(DateTimeInterface $date): string
    {
        return $date->format('l jS F Y, g:ia');
    }


    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }


    /**
     * Create a new factory instance for the model.
     *
     * @return Factory
     */
    protected static function newFactory(): Factory
    {
        return UserFactory::new();
    }



}

app/Http/Controllers/Users/DashController.php
<?php
/**
 * DashController | actions for views/users
 *
 * @package Users
 * @author Andre Board <dre.board@gmail.com>
 * @version 1.0
 * @access public
 * @see https://github.com/dreboard/coin-app
 * @copyright none
 */
namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Models\Groups\Group;
use App\Models\Policy;
use App\Repositories\User\UserMessageRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\DB;

class DashController extends Controller
{

    public function __construct(private UserMessageRepository $userMessageRepository)
    {

    }

    /**
     * Main dashboard view
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        $group = Group::select('id')->where('user_id', auth()->user()->id)->first();
        $messageCount = $this->userMessageRepository->getUserMessageCount(auth()->user()->id);
        $systemMessageCount = $this->userMessageRepository->getUserSystemMessageCount(auth()->user()->id);
        return view('users.dashboard',[
            'pageTitle' => 'My Dashboard',
            'messageCount' => $messageCount,
            'systemMessageCount' => $systemMessageCount,
            'group' => $group,
        ]);
    }

    /**
     * New User Page
     *
     * @return Factory|View|Application
     */
    public function newUser(): Factory|View|Application
    {
        return view('users.intro.index');
    }


    /**
     * Main policy page
     * @return Factory|View|Application
     */
    public function viewPolicyPage(): Factory|View|Application
    {
        return view('users.policies');
    }

    /**
     * View a policy
     *
     * @param int $id
     * @return \Application|\Factory|\View
     * @todo all policies
     */
    public function viewPolicyTypePage(int $id): \Application|\Factory|\View
    {
        $policy_type = Policy::find($id);
        $policy_type2 = DB::table('policies')->where('id', '=', $id)->first();
        //dd($policy_type);
        return view('users.policy_type', [
            'policy_type' => $policy_type,
            'pageTitle' => $policy_type->title
        ]);
    }



}

resources/views/users/settings/profile.blade.php
@extends('layouts.user.main')
@section('pageTitle', 'My Profile Settings')
@section('content')
    <div class="row">
        <div class="col-6 float-start">
            <h3 class="mt-4">My Profile Settings</h3>
        </div>
        <div class="col-6">
            <div class="dropdown mt-4 float-end">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1"
                        data-bs-toggle="dropdown" aria-expanded="false">
                    Public Profile
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item"
                           href="{{ route('user.public', ['id' => auth()->user()->id]) }}">View</a></li>
                    <li><a class="dropdown-item"
                           href="{{ route('user.edit_public', ['user' => auth()->user()->id]) }}">Edit</a></li>
                </ul>
            </div>
        </div>
    </div>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{ route('user.dashboard') }}">Dashboard</a></li>
    </ol>
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{asset('storage/'.auth()->user()->avatar)}}" width="100" alt="" />
                                <div class="mt-3">
                                    <h4>{{ auth()->user()->name }}</h4>
                                    <p class="text-secondary mb-1">Basic Collector</p>
                                    <a class="btn btn-outline-primary" href="{{ route('user.user_edit_avatar', ['user' => auth()->user()->id]) }}"
                                            @if( auth()->user()->status == 'warn') disabled @endif>Change
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="deleteUserModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteUserModalLabel">
                                        Delete {{ auth()->user()->name }}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    You are about to delete the account for {{ auth()->user()->name }}, and all content.
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close
                                    </button>
                                    <a class="btn btn-danger"
                                       href="{{ route('user.user_delete_account', ['user_id' => auth()->user()->id])  }}"
                                       role="button">YES</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card mt-3">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Member Since</h6>
                                <span
                                    class="text-secondary">{{ date('D jS M Y, g:ia', strtotime(auth()->user()->created_at)) }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Last Login</h6>
                                <span class="text-secondary">{{ $last_login ?? 'No Info' }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0 @if( auth()->user()->status == 'warn') text-danger @endif">Messages</h6>
                                <span class="text-secondary">88: <a
                                        href="{{ route('user.message_all') }}">View</a></span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">MemberSince</h6>
                                <span class="text-secondary">httcom</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">MemberSince</h6>
                                <span class="text-secondary">httcom</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">{{ auth()->user()->name }}</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <a class="btn btn-info @if( auth()->user()->status == 'warn') invisible @endif"
                                       href=" {{ route('user.user_change_password') }} ">Change Username</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">{{ auth()->user()->email }}</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <a class="btn btn-info @if( auth()->user()->status == 'warn') invisible @endif"
                                       href=" {{ route('user.user_change_email') }} ">Change Email</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Visibility</h6>
                                </div>
                                <div class="col-sm-9 text-secondary" id="profile_visibility"
                                     data-visibility="{{ auth()->user()->profile_visibility }}">
                                    <!-- Checked switch -->
                                    <div class="form-check form-switch" id="profile_visibility_on">
                                        <input
                                            class="form-check-input @if( auth()->user()->status == 'warn') invisible @endif"
                                            type="checkbox" role="switch" id="profile_visibility_check"
                                            value="{{ auth()->user()->profile_visibility }}"
                                            {{ (auth()->user()->profile_visibility == 1 ? 'checked' : '')}}
                                        />
                                        <label
                                            class="form-check-label {{ (auth()->user()->profile_visibility == 1 ? 'text-success' : 'text-danger')}}"
                                            for="profile_visibility_check" id="profile_visibility_label">
                                            {{ (auth()->user()->profile_visibility == 1 ? 'Public' : 'Private')}}
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Security</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <a class="btn btn-info @if( auth()->user()->status == 'warn') invisible @endif"
                                       href=" {{ route('user.user_change_password') }} ">Change Password</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Account Details</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <a class="btn btn-info @if( auth()->user()->status == 'warn') invisible @endif"
                                       href="{{ route('user.edit_public', ['user' => auth()->user()->id]) }}">Edit</a>
                                </div>
                            </div>

                            <hr>
                            <div class="row">
                                <div class="col-sm-12">
                                    <button id="delete_user" class="btn btn-danger" data-bs-toggle="modal"
                                            data-bs-target="#deleteUserModal">Delete Account
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                    </div>
                </div>
            </div>


    @push('scripts')
        <script>
            (function () {
                try {
                    // profile_visibility_on
                    const pro_vis = document.getElementById("profile_visibility_check").value;
                    const profile_visibility_label = document.getElementById("profile_visibility_label");
                    document.getElementById("profile_visibility_check").addEventListener('click', getData);
                    if (typeof pro_vis !== 'undefined') {
                        console.log(pro_vis);
                    } else {
                        console.log('nope');
                    }
                    console.log(SITE_URL);
                    console.log(ENVIRONMENT);
                    console.log(CSRF_TOKEN);
                    console.log(USER_ID);

                    function getData() {
                        fetch(SITE_URL + '/user/user_change_visibility', {
                            headers: {"Content-Type": "application/json; charset=utf-8"},
                            method: 'POST',
                            body: JSON.stringify({
                                _token: @json(csrf_token()),
                                id: {{ auth()->user()->id }},
                                profile_visibility: document.getElementById("profile_visibility_check").value
                            })
                        }).then(response => response.json())
                            .then(data => {
                                document.getElementById("profile_visibility_check").value = data;
                                if (data == 1) {
                                    profile_visibility_label.innerHTML = 'Public';
                                    profile_visibility_label.classList.add('text-success');
                                    profile_visibility_label.classList.remove('text-danger');
                                } else {
                                    profile_visibility_label.innerHTML = 'Private';
                                    profile_visibility_label.classList.add('text-danger');
                                    profile_visibility_label.classList.remove('text-success');
                                }
                                console.log('Success:', data);
                                console.log(profile_visibility_label.innerHTML);
                            })
                        //.then(data => console.log(data))
                    }
                } catch (error) {
                    if (ENVIRONMENT === 'local') {
                        console.error(error);
                    }
                }
            })();
        </script>
    @endpush
@endsection