routes/admin.php
<?php
use App\Http\Controllers\Admin\AdminBanUserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserActionsController;
use App\Http\Controllers\Admin\AdminViolateUserController;
use App\Http\Controllers\Admin\AdminWarnUserController;
use Illuminate\Support\Facades\Route;
/*
|-------------------------------------------------------------------------------
| Admin section
|-------------------------------------------------------------------------------
| Prefix:         admin/ OR .admin
| Controller:     Admin/AdminController
| Method:         MIXED
| Description:    Admin actions
*/
Route::middleware(['auth', 'verified'])->group(function () {

    Route::prefix('admin')
        ->middleware(['is_admin'])
        ->name('admin.')
        ->group(function () {

            Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

            // User actions
            Route::controller(AdminUserActionsController::class)->group(function () {
                Route::get('/view_user/{user_id}', 'viewUser')->name('view_user')->where('user_id', '[0-9]+');
                Route::get('/view_user_logins/{user_id}', 'viewUserLogins')->name('view_user_logins')->where('user_id', '[0-9]+');
                Route::get('/view_users', 'viewAllUsers')->name('view_users');
                Route::post('/find_user', 'findUser')->name('find_user');
                Route::post('/verify_user', 'verifyUser')->name('verify_user');
                Route::get('/delete_user/{user_id}', 'deleteUser')->name('delete_user')->where('user_id', '[0-9]+');
                Route::get('/user_status/{user_id}', 'changeUserStatus')->name('user_status')->where('user_id', '[0-9]+');
                // messages
                Route::get('/message_new', 'newMessage')->name('message_new');
                Route::post('/message_system_save', 'saveUserMessage')->name('message_system_save');
                Route::get('/message_user/{user_id}', 'newUserMessage')->name('message_user')->where('user_id', '[0-9]+');
                Route::post('/message_user_save', 'saveUserMessage')->name('message_user_save');
                // Clone users
                Route::get('/clone_user/{user_id}', 'cloneUser')->name('clone_user')->where('user_id', '[0-9]+');

            });


            // Group actions
            Route::controller(\App\Http\Controllers\Admin\GroupController::class)->group(function () {
                // Viewing
                Route::get('/group_all', 'viewGroups')->name('group_all');
                Route::get('/group_view/{id}', 'viewGroup')->name('group_view')->where('id', '[0-9]+');


            });
            // Warned users
            Route::post('/warn_user', [AdminWarnUserController::class, 'warnUser'])->name('warn_user');

            // Banned users
            Route::controller(AdminBanUserController::class)->group(function () {
                Route::post('/ban_user', 'banUser')->name('ban_user');
                Route::get('/unban_user/{user_id}', 'unbanUser')->name('unban_user')->where('user_id', '[0-9]+');
                Route::get('/unban_all_users', 'unbanAllExpiredBannedUsers')->name('unban_all_users');
                Route::get('/view_banned_users', 'viewAllBannedUsers')->name('view_banned_users');
            });

            // Violations reported users
            Route::controller(AdminViolateUserController::class)->group(function () {
                Route::get('/violation_pending', 'viewAllPendingViolations')->name('violation_pending');
                Route::get('/violation_all', 'viewAllViolations')->name('violation_all');
                Route::get('/reported_type/{violation_type}', 'viewAllViolationsByType')->name('reported_type');
                Route::get('/violations_by_user/{user_id}', 'viewReportedByUserViolations')->name('violations_by_user')->where('user_id', '[0-9]+');
                Route::get('/violations_against_user/{user_id}', 'viewReportedAgainstUserViolations')->name('violations_against_user')->where('user_id', '[0-9]+');
            });


        });

});

routes/web.php
<?php


use App\Http\Controllers\BannedController;
use App\Http\Controllers\Groups\ClubController;
use App\Http\Controllers\News\RSSController;
use App\Http\Controllers\News\VideoController;
use App\Http\Controllers\System\MessageController;
use App\Http\Controllers\Users\DashController;
use App\Http\Controllers\Users\UserActionsController;
use App\Http\Controllers\Users\UserController;
use App\Http\Controllers\Users\UserViolationsController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

try {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/clear_cache', function() {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('event:clear');
        $exitCode = Artisan::call('route:clear');
        $exitCode = Artisan::call('view:clear');
        return 'DONE'; //Return anything
    });

    Route::get('/banned', [BannedController::class, 'banned'])->name('banned');
    Route::post('/restore_ban', [BannedController::class, 'restoreBan'])->name('restore_ban');
    /*
    |--------------------------------------------------------------------------
    | Site web Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::middleware(['auth', 'verified'])->group(function () {

        Route::get('/policies', [DashController::class, 'viewPolicyPage'])->name('policies');
        Route::get('/view_policy/{id}', [DashController::class, 'viewPolicyTypePage'])->name('view_policy');


        /*
        |-------------------------------------------------------------------------------
        | User section
        |-------------------------------------------------------------------------------
        | Prefix:         user/ OR .user
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    User actions
        */
        Route::prefix('user')
            ->name('user.')
            ->middleware(['is_banned', 'is_online'])
            //->middleware(['forbid-banned-user', 'is_online'])
            ->group(function () {

                // General routes and settings
                Route::controller(DashController::class)->group(function () {
                    Route::get('/dashboard', 'index')->name('dashboard');
                });


                Route::controller(UserController::class)->group(function () {
                    Route::get('/user_profile', 'viewProfile')->name('user_profile');
                    Route::get('/directory', 'viewDirectory')->name('directory')->middleware('is_warned');
                    Route::get('/public/{id}', 'viewPublicProfile')->name('public')->middleware('is_warned');
                    Route::get('/warning_page', 'viewWarningPage')->name('warning_page');
                });

                Route::middleware(['is_warned'])->group(function () {

                    // Basic account actions
                    Route::controller(UserActionsController::class)->group(function () {
                        Route::get('/user_change_password', 'changePassword')->name('user_change_password');
                        Route::post('/user_save_password', 'savePassword')->name('user_save_password');
                        Route::get('/user_change_email', 'changeEmail')->name('user_change_email');
                        Route::post('/user_save_email', 'saveEmail')->name('user_save_email');
                        Route::post('/user_change_visibility', 'toggleVisibility')->name('user_change_visibility');
                        Route::post('/user_delete_account', 'deleteAccount')->name('user_delete_account');
                    });

                    // Violations
                    Route::controller(UserViolationsController::class)->group(function () {
                        Route::get('/violation_create', 'violationCreate')->name('violation_create');
                        Route::post('/violation_update', 'violationUpdate')->name('violation_update');
                        Route::post('/violation_save', 'violationSave')->name('violation_save');
                        Route::get('/violation_view/{id}', 'violationView')->name('violation_view');
                        Route::get('/violation_reported', 'violationViewReported')->name('violation_reported');
                        Route::get('/violation_against_user', 'violationViewReportedAgainst')->name('violation_against_user');
                    });

                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Clubs section
        |-------------------------------------------------------------------------------
        | Prefix:         club/ OR .club
        | Controller:     Groups/ClubController, ManageClubController
        | Method:         MIXED
        | Description:    Group actions
        */
        Route::prefix('club')
            ->name('club.')
            ->middleware(['is_banned', 'is_warned'])
            ->group(function () {

                // Basic routes
                Route::controller(ClubController::class)->group(function () {
                    Route::get('/view/{id}', 'view')->name('view');
                    Route::get('/edit/{id}', 'create')->name('edit');
                    Route::post('/update', 'create')->name('update');
                    Route::post('/delete_all', 'destroyAll')->name('delete_all');
                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Messages section
        |-------------------------------------------------------------------------------
        | Prefix:         messages/ OR .messages
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    messages actions
        */
        Route::prefix('messages')
            ->name('messages.')
            ->group(function () {
                Route::middleware(['is_warned'])->controller(MessageController::class)->group(function () {
                    Route::get('/', 'index')->name('messages');
                    Route::get('/create', 'create')->name('create');
                    Route::post('/', 'store')->name('store');
                    Route::get('{id}', 'show')->name('show');
                    Route::put('{id}', 'update')->name('update');
                });
       });

        /*
        |-------------------------------------------------------------------------------
        | News section
        |-------------------------------------------------------------------------------
        | Prefix:         news/ OR .news
        | Controller:     News/RSSController
        | Method:         MIXED
        | Description:    news actions
        */
        Route::prefix('news')
            ->name('news.')
            ->group(function () {
                Route::controller(RSSController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('feed/{slug}', 'loadFeed')->name('feed');
                    Route::get('ana', 'getANA')->name('ana');
                });
            });

        /*
        |-------------------------------------------------------------------------------
        | Video section
        |-------------------------------------------------------------------------------
        | Prefix:         video/ OR .video
        | Controller:     News/VideoController
        | Method:         MIXED
        | Description:    Video actions
        */
        Route::prefix('video')
            ->name('video.')
            ->group(function () {
                Route::controller(VideoController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('channel/{slug}', 'loadChannel')->name('channel');
                    Route::get('playlist/{slug}', 'loadChannel')->name('playlist');
                    Route::get('url', 'loadChannel')->name('url');
                    Route::get('search', 'loadSearchVideos')->name('search');
                });
            });


    });



    /*
    |-------------------------------------------------------------------------------
    | Auth Routes
    |-------------------------------------------------------------------------------
    | Prefix:         NONE
    | Controller:     RegisteredUserController, AuthenticatedSessionController, PasswordResetLinkController
    | Method:         MIXED
    | Description:    Auth routes
    */
    require __DIR__.'/auth.php';

}catch (\Throwable $e){
    Log::error($e->getMessage());
    return view('welcome');
}

app/Models/Groups/Library.php
<?php
/**
 * Library | Model for Group library
 *
 * @package Groups
 * @subpackage Media
 * @author Andre Board <dre.board@gmail.com>
 * @version 1.0
 * @access public
 * @see https://github.com/dreboard/coin-app
 * @copyright none
 */
namespace App\Models\Groups;

use App\Models\User;
use Database\Factories\Groups\LibraryFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Library extends Model
{
    use HasFactory;

    protected $table = 'library';

    protected $fillable = [
        'group_id',
        'publication_type',
        'publication_title',
        'isbn',
        'details',
        'value',
        'status',
        'received'
    ];


    /**
     * Get the agendas for the event.
     */
    public function lendees(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'library_user', 'library_id', 'user_id')
            ->withTimestamps();
    }

    /**
     * Create a new factory instance for the model.
     *
     * @return LibraryFactory
     */
    protected static function newFactory(): LibraryFactory
    {
        return LibraryFactory::new();
    }
}

app/Http/Controllers/Groups/LibraryController.php
<?php

namespace App\Http\Controllers\Groups;

use App\Http\Controllers\Controller;

class LibraryController extends Controller
{
    //
}

resources/views/library/dashboard.blade.php
@extends('layouts.user.main')

@section('title', 'My Dashboard')

@section('sidebar')
    @parent

    <p>This is appended to the master sidebar.</p>
@endsection

@section('content')

    <h1 class="mt-4">My Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Home</li>
    </ol>
    <p>My Collection</p>

    <div class="table-responsive">
        <table class="table table-sm table-borderless">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>@fat</td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td colspan="2">Larry the Bird</td>
                <td>@twitter</td>
            </tr>
            </tbody>
        </table>
    </div>



    <div class="card-group">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">My Projects</h5>
                <ul class="list-group list-group-flush">
                    <a href="#" class="list-group-item list-group-item-action">Project 1</a>
                    <a href="#" class="list-group-item list-group-item-action">Project 2</a>
                    <a href="#" class="list-group-item list-group-item-action">Project 3</a>
                </ul>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Groups</h5>
                <p class="card-text"><a href="{{ route('group.all') }}" class="list-group-item list-group-item-action">See All</a></p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                @if(is_null($group))
                    <a href="{{ route('group.start') }}" class="list-group-item list-group-item-action">Create</a>
                @else
                    <a href="{{ route('group.mine') }}" class="list-group-item list-group-item-action">My Groups</a>
                @endif
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <ul class="list-group list-group-flush">
                <a href="{{ route('user.message_all') }}" class="list-group-item list-group-item-action">
                    <span class="@if($systemMessageCount > 0) text-danger @endif @if(auth()->user()->status === 'warn') text-danger @endif">
                        System Messages
                    </span>
                    <span class="badge @if($systemMessageCount > 0) bg-danger @else bg-primary @endif rounded-pill">{{ $systemMessageCount }}</span>
                </a>
                @good
                    <a href="{{ route('messages.messages') }}" class="list-group-item list-group-item-action">User Messages <span class="badge bg-primary rounded-pill">{{$messageCount}}</span></a>
                    <a href="{{ route('user.view_directory') }}" class="list-group-item list-group-item-action">User Directory</a>
                @endgood
                <a href="{{ route('user.view_directory') }}" class="list-group-item list-group-item-action">Shop</a>
                <a href="{{ route('user.view_directory') }}" class="list-group-item list-group-item-action">News</a>
            </ul>
            <div class="card-footer">
                Card footer
            </div>
        </div>
    </div>


    <div class="card-group">
        <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Shop</h5>
                <p class="card-text">This is a widontent is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
        <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">News</h5>
                <p class="card-text">This card has supporting text onal content.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
        <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">This is a wider car card haeight action.</p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
        </div>
    </div>

@endsection