routes/admin.php
<?php
use App\Http\Controllers\Admin\AdminBanUserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserActionsController;
use App\Http\Controllers\Admin\AdminViolateUserController;
use App\Http\Controllers\Admin\AdminWarnUserController;
use Illuminate\Support\Facades\Route;
/*
|-------------------------------------------------------------------------------
| Admin section
|-------------------------------------------------------------------------------
| Prefix:         admin/ OR .admin
| Controller:     Admin/AdminController
| Method:         MIXED
| Description:    Admin actions
*/
Route::middleware(['auth', 'verified'])->group(function () {

    Route::prefix('admin')
        ->middleware(['is_admin'])
        ->name('admin.')
        ->group(function () {

            Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

            // User actions
            Route::controller(AdminUserActionsController::class)->group(function () {
                Route::get('/view_user/{user_id}', 'viewUser')->name('view_user')->where('user_id', '[0-9]+');
                Route::get('/view_user_logins/{user_id}', 'viewUserLogins')->name('view_user_logins')->where('user_id', '[0-9]+');
                Route::get('/view_users', 'viewAllUsers')->name('view_users');
                Route::post('/find_user', 'findUser')->name('find_user');
                Route::post('/verify_user', 'verifyUser')->name('verify_user');
                Route::get('/delete_user/{user_id}', 'deleteUser')->name('delete_user')->where('user_id', '[0-9]+');
                Route::get('/user_status/{user_id}', 'changeUserStatus')->name('user_status')->where('user_id', '[0-9]+');
                // messages
                Route::get('/message_new', 'newMessage')->name('message_new');
                Route::post('/message_system_save', 'saveUserMessage')->name('message_system_save');
                Route::get('/message_user/{user_id}', 'newUserMessage')->name('message_user')->where('user_id', '[0-9]+');
                Route::post('/message_user_save', 'saveUserMessage')->name('message_user_save');
                // Clone users
                Route::get('/clone_user/{user_id}', 'cloneUser')->name('clone_user')->where('user_id', '[0-9]+');

            });


            // Group actions
            Route::controller(\App\Http\Controllers\Admin\GroupController::class)->group(function () {
                // Viewing
                Route::get('/group_all', 'viewGroups')->name('group_all');
                Route::get('/group_view/{id}', 'viewGroup')->name('group_view')->where('id', '[0-9]+');


            });
            // Warned users
            Route::post('/warn_user', [AdminWarnUserController::class, 'warnUser'])->name('warn_user');

            // Banned users
            Route::controller(AdminBanUserController::class)->group(function () {
                Route::post('/ban_user', 'banUser')->name('ban_user');
                Route::get('/unban_user/{user_id}', 'unbanUser')->name('unban_user')->where('user_id', '[0-9]+');
                Route::get('/unban_all_users', 'unbanAllExpiredBannedUsers')->name('unban_all_users');
                Route::get('/view_banned_users', 'viewAllBannedUsers')->name('view_banned_users');
            });

            // Violations reported users
            Route::controller(AdminViolateUserController::class)->group(function () {
                Route::get('/violation_pending', 'viewAllPendingViolations')->name('violation_pending');
                Route::get('/violation_all', 'viewAllViolations')->name('violation_all');
                Route::get('/reported_type/{violation_type}', 'viewAllViolationsByType')->name('reported_type');
                Route::get('/violations_by_user/{user_id}', 'viewReportedByUserViolations')->name('violations_by_user')->where('user_id', '[0-9]+');
                Route::get('/violations_against_user/{user_id}', 'viewReportedAgainstUserViolations')->name('violations_against_user')->where('user_id', '[0-9]+');
            });


        });

});

routes/web.php
<?php


use App\Http\Controllers\BannedController;
use App\Http\Controllers\Groups\ClubController;
use App\Http\Controllers\News\RSSController;
use App\Http\Controllers\News\VideoController;
use App\Http\Controllers\System\MessageController;
use App\Http\Controllers\Users\DashController;
use App\Http\Controllers\Users\UserActionsController;
use App\Http\Controllers\Users\UserController;
use App\Http\Controllers\Users\UserViolationsController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

try {

    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/clear_cache', function() {
        $exitCode = Artisan::call('config:clear');
        $exitCode = Artisan::call('cache:clear');
        $exitCode = Artisan::call('event:clear');
        $exitCode = Artisan::call('route:clear');
        $exitCode = Artisan::call('view:clear');
        return 'DONE'; //Return anything
    });

    Route::get('/banned', [BannedController::class, 'banned'])->name('banned');
    Route::post('/restore_ban', [BannedController::class, 'restoreBan'])->name('restore_ban');
    /*
    |--------------------------------------------------------------------------
    | Site web Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::middleware(['auth', 'verified'])->group(function () {

        Route::get('/policies', [DashController::class, 'viewPolicyPage'])->name('policies');
        Route::get('/view_policy/{id}', [DashController::class, 'viewPolicyTypePage'])->name('view_policy');


        /*
        |-------------------------------------------------------------------------------
        | User section
        |-------------------------------------------------------------------------------
        | Prefix:         user/ OR .user
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    User actions
        */
        Route::prefix('user')
            ->name('user.')
            ->middleware(['is_banned', 'is_online'])
            //->middleware(['forbid-banned-user', 'is_online'])
            ->group(function () {

                // General routes and settings
                Route::controller(DashController::class)->group(function () {
                    Route::get('/dashboard', 'index')->name('dashboard');
                });


                Route::controller(UserController::class)->group(function () {
                    Route::get('/user_profile', 'viewProfile')->name('user_profile');
                    Route::get('/directory', 'viewDirectory')->name('directory')->middleware('is_warned');
                    Route::get('/public/{id}', 'viewPublicProfile')->name('public')->middleware('is_warned');
                    Route::get('/warning_page', 'viewWarningPage')->name('warning_page');
                });

                Route::middleware(['is_warned'])->group(function () {

                    // Basic account actions
                    Route::controller(UserActionsController::class)->group(function () {
                        Route::get('/user_change_password', 'changePassword')->name('user_change_password');
                        Route::post('/user_save_password', 'savePassword')->name('user_save_password');
                        Route::get('/user_change_email', 'changeEmail')->name('user_change_email');
                        Route::post('/user_save_email', 'saveEmail')->name('user_save_email');
                        Route::post('/user_change_visibility', 'toggleVisibility')->name('user_change_visibility');
                        Route::post('/user_delete_account', 'deleteAccount')->name('user_delete_account');
                    });

                    // Violations
                    Route::controller(UserViolationsController::class)->group(function () {
                        Route::get('/violation_create', 'violationCreate')->name('violation_create');
                        Route::post('/violation_update', 'violationUpdate')->name('violation_update');
                        Route::post('/violation_save', 'violationSave')->name('violation_save');
                        Route::get('/violation_view/{id}', 'violationView')->name('violation_view');
                        Route::get('/violation_reported', 'violationViewReported')->name('violation_reported');
                        Route::get('/violation_against_user', 'violationViewReportedAgainst')->name('violation_against_user');
                    });

                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Clubs section
        |-------------------------------------------------------------------------------
        | Prefix:         club/ OR .club
        | Controller:     Groups/ClubController, ManageClubController
        | Method:         MIXED
        | Description:    Group actions
        */
        Route::prefix('club')
            ->name('club.')
            ->middleware(['is_banned', 'is_warned'])
            ->group(function () {

                // Basic routes
                Route::controller(ClubController::class)->group(function () {
                    Route::get('/view/{id}', 'view')->name('view');
                    Route::get('/edit/{id}', 'create')->name('edit');
                    Route::post('/update', 'create')->name('update');
                    Route::post('/delete_all', 'destroyAll')->name('delete_all');
                });


            });

        /*
        |-------------------------------------------------------------------------------
        | Messages section
        |-------------------------------------------------------------------------------
        | Prefix:         messages/ OR .messages
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    messages actions
        */
        Route::prefix('messages')
            ->name('messages.')
            ->group(function () {
                Route::middleware(['is_warned'])->controller(MessageController::class)->group(function () {
                    Route::get('/', 'index')->name('messages');
                    Route::get('/create', 'create')->name('create');
                    Route::post('/', 'store')->name('store');
                    Route::get('{id}', 'show')->name('show');
                    Route::put('{id}', 'update')->name('update');
                });
       });

        /*
        |-------------------------------------------------------------------------------
        | News section
        |-------------------------------------------------------------------------------
        | Prefix:         news/ OR .news
        | Controller:     News/RSSController
        | Method:         MIXED
        | Description:    news actions
        */
        Route::prefix('news')
            ->name('news.')
            ->group(function () {
                Route::controller(RSSController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('feed/{slug}', 'loadFeed')->name('feed');
                    Route::get('ana', 'getANA')->name('ana');
                });
            });

        /*
        |-------------------------------------------------------------------------------
        | Video section
        |-------------------------------------------------------------------------------
        | Prefix:         video/ OR .video
        | Controller:     News/VideoController
        | Method:         MIXED
        | Description:    Video actions
        */
        Route::prefix('video')
            ->name('video.')
            ->group(function () {
                Route::controller(VideoController::class)->group(function () {
                    Route::get('all', 'index')->name('all');
                    Route::get('channel/{slug}', 'loadChannel')->name('channel');
                    Route::get('playlist/{slug}', 'loadChannel')->name('playlist');
                    Route::get('url', 'loadChannel')->name('url');
                    Route::get('search', 'loadSearchVideos')->name('search');
                });
            });


    });



    /*
    |-------------------------------------------------------------------------------
    | Auth Routes
    |-------------------------------------------------------------------------------
    | Prefix:         NONE
    | Controller:     RegisteredUserController, AuthenticatedSessionController, PasswordResetLinkController
    | Method:         MIXED
    | Description:    Auth routes
    */
    require __DIR__.'/auth.php';

}catch (\Throwable $e){
    Log::error($e->getMessage());
    return view('welcome');
}

app/Models/Users/Login.php
<?php

namespace App\Models\Users;

use App\Models\User;
use Database\Factories\UserFactory;
use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Login extends Model
{
    use HasFactory;

    //protected $dateFormat = 'l jS F Y, g:ia';
    public $timestamps = false;
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime:l jS F Y, g:ia',
    ];

    /**
     * Prepare a date for array / JSON serialization.
     *
     * @param DateTimeInterface $date
     * @return string
     */
    protected function serializeDate(DateTimeInterface $date): string
    {
        return $date->format('l jS F Y, g:ia');
    }


    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }


    /**
     * Create a new factory instance for the model.
     *
     * @return Factory
     */
    protected static function newFactory(): Factory
    {
        return UserFactory::new();
    }



}

app/Models/Users/Warning.php
<?php

namespace App\Models\Users;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Warning extends Model
{
    use HasFactory;

    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'user_id',
        'created_at'
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Users/DashController.php
<?php
/**
 * DashController | actions for views/users
 *
 * @package Users
 * @author Andre Board <dre.board@gmail.com>
 * @version 1.0
 * @access public
 * @see https://github.com/dreboard/coin-app
 * @copyright none
 */
namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Models\Groups\Group;
use App\Models\Policy;
use App\Repositories\User\UserMessageRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\DB;

class DashController extends Controller
{

    public function __construct(private UserMessageRepository $userMessageRepository)
    {

    }

    /**
     * Main dashboard view
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        $group = Group::select('id')->where('user_id', auth()->user()->id)->first();
        $messageCount = $this->userMessageRepository->getUserMessageCount(auth()->user()->id);
        $systemMessageCount = $this->userMessageRepository->getUserSystemMessageCount(auth()->user()->id);
        return view('users.dashboard',[
            'pageTitle' => 'My Dashboard',
            'messageCount' => $messageCount,
            'systemMessageCount' => $systemMessageCount,
            'group' => $group,
        ]);
    }

    /**
     * New User Page
     *
     * @return Factory|View|Application
     */
    public function newUser(): Factory|View|Application
    {
        return view('users.intro.index');
    }


    /**
     * Main policy page
     * @return Factory|View|Application
     */
    public function viewPolicyPage(): Factory|View|Application
    {
        return view('users.policies');
    }

    /**
     * View a policy
     *
     * @param int $id
     * @return \Application|\Factory|\View
     * @todo all policies
     */
    public function viewPolicyTypePage(int $id): \Application|\Factory|\View
    {
        $policy_type = Policy::find($id);
        $policy_type2 = DB::table('policies')->where('id', '=', $id)->first();
        //dd($policy_type);
        return view('users.policy_type', [
            'policy_type' => $policy_type,
            'pageTitle' => $policy_type->title
        ]);
    }



}

resources/views/admin/user/view.blade.php
@extends('layouts.admin.main')

@section('title', 'Page Title')

@section('sidebar')
    @parent

    <p>This is appended to the master sidebar.</p>
@endsection

@section('content')
    <h3 class="mt-4">#{{$user->id}} {{ $user->name }}</h3>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a> </li>
        <li class="breadcrumb-item active"><a href="{{ route('admin.view_users') }}">Users</a></li>
    </ol>

    <div class="container">
        <div class="main-body">

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        @if($user->is_admin != 1)
                            <a class="btn btn-outline-primary" href="{{ route('admin.message_user', $user->id) }}" role="button">Message</a>

                            @if (!$user->canBeImpersonated())
                                <a class="btn btn-warning" href="{{ route('admin.clone_user', $user->id) }}" role="button">Clone</a>
                            @endif
                            @canBeImpersonated($user)
                            <a class="btn btn-warning" href="{{ route('admin.clone_user', $user->id) }}" role="button">Clone</a>
                            @endCanBeImpersonated

                            <button id="delete_user" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteUserModal">Delete</button>
                        @endif
                    </div>

                    <div class="modal fade" id="deleteUserModal" tabindex="-1" aria-labelledby="deleteUserModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteUserModalLabel">Delete {{ $user->name }}</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    You are about to delete {{ $user->name }}, and all content.
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a class="btn btn-danger" href="{{ route('admin.delete_user', ['user_id' => $user->id])  }}" role="button">YES</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card mt-3">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Email</h6>
                                <span class="text-secondary">{{ $user->email }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Logins</h6>
                                <span class="text-secondary"><a href="{{ route('admin.view_user_logins', $user->id) }}" role="button">Logins: {{ $user->logins_count }}</a></span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Bans</h6>
                                <span class="text-secondary">{{ $user->bans_count }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Warnings</h6>
                                <span class="text-secondary">{{ $user->warnings_count }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Violations By</h6>
                                <span class="text-secondary"><a href="{{ route('admin.violations_by_user', $user->id) }}" role="button">Violations: {{ $user->violations_count }}</a></span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">Violations Against</h6>
                                <span class="text-secondary"><a href="{{ route('admin.violations_against_user', $user->id) }}" role="button">Violations: {{ $reported }} </a></span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">

                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Site Status</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <span class="text-secondary">@if(Cache::has('user-is-online-' . $user->id))
                                            <span class="text-success">Online</span>
                                        @else
                                            <span class="text-danger">Offline</span>
                                        @endif</span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Warning Status</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">

                                        <form class="row row-cols-lg-auto g-3 align-items-center" method="POST" action="{{ route('admin.warn_user')  }}">
                                            @csrf
                                            <input type="hidden" name="user_id" value="{{$user->id}}">

                                            @if($user->status == 'good')
                                                <span class="text-success">Good</span>
                                                <input type="hidden" name="status" value="warn">
                                                <div class="col-4">
                                                    <button type="submit" class="btn btn-warning">Warn</button>
                                                </div>
                                            @else
                                                <span class="text-warning">Warning</span>
                                                <input type="hidden" name="status" value="good">
                                                <div class="col-4">
                                                    <button type="submit" class="btn btn-success">Restore</button>
                                                </div>
                                            @endif
                                        </form>

                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Last Login</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                @empty($last_login->created_at)
                                        <span class="text-danger">No Login Data</span>
                                    @else
                                        {{$last_login->created_at->format('l jS F Y, g:ia')}}
                                    @endempty
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    @empty($user->email_verified_at)
                                        <span class="text-danger">Unverified</span>
                                    @else
                                        <span class="text-success">Verified</span>
                                    @endempty
                                 </div>
                                <div class="col-sm-9 text-secondary">
                                    @empty($user->email_verified_at)
                                        <form class="row row-cols-lg-auto g-3 align-items-center" method="POST" action="{{ route('admin.verify_user')  }}">
                                            @csrf
                                            <input type="hidden" name="user_id" value="{{$user->id}}">
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-danger">Verify User</button>
                                            </div>
                                        </form>

                                    @else
                                        {{ $user->email_verified_at->format('l jS F Y, g:ia') ?? 'No Data' }}
                                    @endempty

                                </div>
                            </div>

                            @if($user->is_admin != 1)
                                <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">
                                        @if($user->isBanned())
                                            <span class="text-danger">Suspended</span>
                                        @else
                                            <span class="text-success">Active</span>
                                        @endif
                                    </h6>
                                </div>

                                <div class="col-sm-9 text-secondary">
                                    @if($user->isBanned())
                                        @if ($user->banned_at == null)
                                            <span class="text-success">Active</span>
                                        @else
                                            <span class="text-danger"> {{ $user->banned_at->format('F jS Y, g:ia') }}</span>
                                        @endif
                                            <a id="status_user" class="btn btn-success" href="{{ route('admin.unban_user', ['user_id' => $user->id])  }}">Activate </a>
                                    @else
                                        <form class="row row-cols-lg-auto g-3 align-items-center" method="POST" action="{{ route('admin.ban_user')  }}">
                                            @csrf
                                            <input type="hidden" name="user_id" value="{{$user->id}}">
                                            <div class="col-8">
                                                <label class="visually-hidden" for="inlineFormSelectPref">Preference</label>
                                                <select class="form-select" name="length">
                                                    <option selected value=""> Suspend User</option>
                                                    <option value="7">1 Week</option>
                                                    <option value="30">1 Month</option>
                                                    <option value="0">Forever</option>
                                                </select>
                                            </div>

                                            <div class="col-4">
                                                <button type="submit" class="btn btn-danger">Suspend</button>
                                            </div>
                                        </form>
                                    @endif

                                </div>
                            </div>
                            @endif
                        </div>
                    </div>

                </div>
            </div>
            <hr />





        </div>
    </div>
@endsection